### ISSUE TITLE
Window too small in 1980x1080 resolution (150% scale)

### ISSUE THREAD

**Issue by Ericboutin** [akmalhakimi1991/mousemover#1]
Window with button too small to interact correctly with, maybe window size should fetch window scale

**150% Scale**
![image](https://user-images.githubusercontent.com/50494834/58843492-abceda80-8640-11e9-9c35-f2ca6a009236.png)

**100% Scale**
![image](https://user-images.githubusercontent.com/50494834/58843574-20097e00-8641-11e9-8db0-f29bd5301c3f.png)

**Comment by Ericboutin** [comment]
Created a branch with quick fix solution

**Comment by akmalmzamri** [comment]
Noted. Do create a Pull Request and I will merge it later

**Comment by Ericboutin** [comment]
Issue closed with merge#3
